# Generated by Django 6.0.3 on 2026-05-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='institutional_id',
            field=models.CharField(default='TEMP000', help_text='Student ID or Staff ID e.g. SGATWI2311', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='Forces user to change password on first login'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('requester', 'Requester (Club Leader / Coach)'), ('approver', 'Approver (Sports Director)'), ('admin', 'Administrator')], default='requester', max_length=20),
        ),
    ]
