# Generated by Django 6.0.3 on 2026-05-03 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('facilities', '0002_facilityzone_recurringblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_priority',
            field=models.BooleanField(default=False, help_text='Priority bookings displace existing bookings. Admin only.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='priority_reason',
            field=models.CharField(blank=True, help_text='Reason for priority e.g. Graduation Ceremony, UEAB Board Meeting', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Specific zone within the facility. Leave blank to book entire facility.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='facilities.facilityzone'),
        ),
        migrations.AddField(
            model_name='conflictlog',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflict_logs', to='facilities.facilityzone'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('displaced', 'Displaced by Priority Event')], default='pending', max_length=20),
        ),
    ]
