# Generated by Django 6.0.3 on 2026-05-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_submitted', 'Booking Submitted'), ('booking_approved', 'Booking Approved'), ('booking_rejected', 'Booking Rejected'), ('booking_cancelled', 'Booking Cancelled'), ('booking_displaced', 'Booking Displaced by Priority Event'), ('conflict_detected', 'Conflict Detected')], max_length=50),
        ),
    ]
